### ISSUE TITLE
Creating Navbar

### ISSUE THREAD

**Issue by AndrewAce** [caffeine-addictt/edutecx#43]
I want to create navbar. 
Navbar bar to have directory to Policy page, contact us page, store page, login or register page (as a button), API page, Help page, and logo.
Features:
- [ ] On hover, to change from white theme to black theme nav bar.
- [ ] Register button on the top right of the screen (Try to be animated)

### Details and Assumptions
*I know how to create a simple navbar with the help of using basic navbar templates from w3schools and bootstrap.  

### Acceptance Criteria     
Finished Product:
- [ ] Able to redirect to the different pages 
- [ ] Working buttons with good styling
- [ ] Able to change theme of nav on scroll
- [ ] Able to highlight the directory of page when a specific pages
